# Generated by Django 4.2.6 on 2023-10-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=150)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('categoria_empresa', models.CharField(max_length=250)),
                ('quitado', models.BooleanField()),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_localizacao', to='reserva.stand')),
            ],
        ),
    ]
